# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3'
services:
  database:
    image: mariadb
    restart: always
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: wikidb
      MYSQL_USER: mediawiki
      MYSQL_PASSWORD: wikidbpw
      MYSQL_ROOT_PASSWORD: wikiexporterpw
    container_name: mariadb
  corpus2wiki:
    build:
      context: ./corpus2wiki
      dockerfile: dockerfile
    restart: always
    links:
      - database
    ports:
      - 8080:80
    container_name: corpus2wiki
    environment:
      - MW_SITE_NAME=MediaWiki
      - MW_SITE_LANG=en
      - MW_DEFAULT_SKIN=vector
      - MW_ENABLE_UPLOADS=1
      - MW_USE_INSTANT_COMMONS=0
      - MW_ADMIN_USER=admin
      - MW_ADMIN_PASS=password
      - MW_DB_NAME=wikidb
      - MW_DB_USER=mediawiki
      - MW_DB_PASS=wikidbpw
      - MW_DB_INSTALLDB_USER=root
      - MW_DB_INSTALLDB_PASS=wikiexporterpw
      - MW_AUTOUPDATE=true
      - MW_MAIN_CACHE_TYPE=None
      - MW_SCRIPT_PATH=
      - MW_SERVER_NAME=http://localhost:8080
